services:
  fastdb:
    container_name: fastdb
    # image: postgres
    image: postgres:latest
    # image: postgres-euckr
    restart: always
    # set shared memory limit when using docker-compose
    # shm_size: 128mb
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD=test1!
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - v-fastdb:/var/lib/postgresql/data \
volumes:
  # v-postgres:
  v-fastdb: